import { ChevronRightIcon } from "@chakra-ui/icons";
import {
  Box,
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  Flex,
  Heading,
  Link,
  VStack,
} from "@chakra-ui/react";
import { ChevronLeft } from "lucide-react";
import Head from "next/head";
import NextLink from "next/link";
import { useRouter } from "next/router";
import * as React from "react";

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const router = useRouter();
  const pathnames = router.asPath.split("/").filter((v) => v);
  const getActiveMenu = (href: string) => router.pathname.includes(href);

  return (
    <>
      <Head>
        <title>Admin Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex>
        <Box flexShrink={0} bg={"gray.50"} h={"100vh"} width={300} p={10}>
          <Heading size="md" as="h1" mb={5}>
            Dashboard
          </Heading>
          <Breadcrumb
            spacing="8px"
            mb={5}
            separator={<ChevronRightIcon color="gray.500" />}
          >
            <BreadcrumbItem>
              <BreadcrumbLink href="/">{"Home"}</BreadcrumbLink>
            </BreadcrumbItem>
            {pathnames.map((pathname, index) => (
              <BreadcrumbItem
                key={pathname}
                isCurrentPage={pathnames.length - 1 == index}
              >
                <BreadcrumbLink
                  color={pathnames.length - 1 == index ? "teal" : ""}
                  href={"/" + pathname}
                  _firstLetter={{ textTransform: "uppercase" }}
                >
                  {pathname}
                </BreadcrumbLink>
              </BreadcrumbItem>
            ))}
          </Breadcrumb>
          <VStack gap={4} align="stretch">
            <Link
              as={NextLink}
              href="/category"
              display={"block"}
              py={2}
              px={6}
              color={getActiveMenu("/category") ? "teal" : ""}
              borderLeftWidth={5}
              borderLeftColor={
                getActiveMenu("/category") ? "teal" : "transparent"
              }
            >
              Kategori
            </Link>
            <Link
              as={NextLink}
              borderLeftWidth={5}
              borderLeftColor={
                getActiveMenu("/operator") ? "teal" : "transparent"
              }
              href="/operator"
              display={"block"}
              color={getActiveMenu("/operator") ? "teal" : ""}
              py={2}
              px={6}
            >
              Operator
            </Link>
          </VStack>
        </Box>
        <Box width={"100%"}>{children}</Box>
      </Flex>
    </>
  );
}
